CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Usuarios` (
  `USU_ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `USU_NOMBRE` VARCHAR(45) NOT NULL,
  `USU_APELLIDO` VARCHAR(45) NOT NULL,
  `USU_USERNAME` VARCHAR(45) NULL,
  `USU_CLAVE` VARCHAR(45) NOT NULL,
  `USU_ESTADO` BIT NULL,
  PRIMARY KEY (`USU_ID_USUARIO`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Canal` (
  `CAN_ID_CANAL` INT NOT NULL AUTO_INCREMENT,
  `CAN_NOMBRE` VARCHAR(45) NOT NULL,
  `CAN_ESTADO` BIT NULL,
  PRIMARY KEY (`CAN_ID_CANAL`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Bancos` (
  `BAN_ID_BANCO` INT NOT NULL AUTO_INCREMENT,
  `BAN_DESCRIPCION` VARCHAR(45) NOT NULL,
  `BAN_ESTADO` BIT NULL,
  PRIMARY KEY (`BAN_ID_BANCO`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Comuna` (
  `COM_ID` INT NOT NULL,
  `COM_NOMBRE` VARCHAR(45) NOT NULL,
  `COM_ESTADO` BIT NULL,
  PRIMARY KEY (`COM_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Estado_Venta` (
  `EST_ID_ESTADO` INT NOT NULL AUTO_INCREMENT,
  `EST_DESCRIPCION` VARCHAR(45) NOT NULL,
  `EST_ESTADO` BIT NULL,
  PRIMARY KEY (`EST_ID_ESTADO`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Categoria` (
  `CAT_ID_CATEGORIA` INT NOT NULL,
  `CAT_DESCRIPCION` VARCHAR(45) NOT NULL,
  `CAT_ESTADO` BIT NULL,
  PRIMARY KEY (`CAT_ID_CATEGORIA`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Marcas` (
  `MAR_ID` INT NOT NULL,
  `MAR_NOMBRE` VARCHAR(45) NOT NULL,
  `MAR_ESTADO` BIT NULL,
  PRIMARY KEY (`MAR_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Cliente` (
  `CLI_ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `CLI_NOMBRE` VARCHAR(45) NOT NULL,
  `CLI_APELLIDO` VARCHAR(45) NOT NULL,
  `CLI_TELEFONO` INT NOT NULL,
  `CLI_CORREO` VARCHAR(45) NOT NULL,
  `CAN_ID_CANAL` INT NOT NULL,
  `CLI_RUT` VARCHAR(15) NULL,
  `CLI_DV` VARCHAR(1) NULL,
  `CLI_ESTADO` BIT NULL,
  PRIMARY KEY (`CLI_ID_CLIENTE`),
  INDEX `fk_cliente_canal_idx` (`CAN_ID_CANAL` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_canal`
    FOREIGN KEY (`CAN_ID_CANAL`)
    REFERENCES `DreamGifts`.`Canal` (`CAN_ID_CANAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Proveedor` (
  `PRO_ID_PROVEEDOR` INT NOT NULL AUTO_INCREMENT,
  `PRO_RAZON_SOCIAL` VARCHAR(45) NOT NULL,
  `PRO_NOMBRE_CONTACTO` VARCHAR(45) NULL,
  `PRO_APELLIDO_CONTACTO` VARCHAR(45) NULL,
  `PRO_TELEFONO` INT NOT NULL,
  `PRO_CORREO` VARCHAR(45) NOT NULL,
  `PRO_DIRECCION` VARCHAR(45) NOT NULL,
  `PRO_RUT` VARCHAR(15) NULL,
  `PRO_DV` VARCHAR(1) NULL,
  `PRO_ESTADO` BIT NULL,
  PRIMARY KEY (`PRO_ID_PROVEEDOR`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Venta` (
  `VTA_ID_VENTA` INT NOT NULL AUTO_INCREMENT,
  `CLI_ID_CLIENTE` INT NOT NULL,
  `PCK_ID_PACK` INT NOT NULL,
  `BAN_ID_BANCO` INT NOT NULL,
  `VTA_TOTAL` INT NOT NULL,
  `VTA_FECHA_VENTA` DATE NOT NULL,
  `VTA_FECHA_TRANSFERENCIA` DATE NOT NULL,
  `VTA_CODIGO_TRANSFERENCIA` INT NOT NULL,
  `VTA_NOMBRE_DESTINATARIO` VARCHAR(50) NOT NULL,
  `VTA_APELLIDO_DESTINATARIO` VARCHAR(45) NOT NULL,
  `VTA_DIRECCION_DESTINATARIO` VARCHAR(45) NOT NULL,
  `COM_ID_COMUNA` INT NOT NULL,
  `VTA_TELEFONO_DESTINATARIO` INT NOT NULL,
  `VTA_FECHA_ENTREGA` DATE NOT NULL,
  `VTA_HORA_ENTREGA_INICIAL` TIME NOT NULL,
  `VTA_HORA_ENTREGA_FINAL` TIME NOT NULL,
  `VTA_SALUDO_TEXTO` VARCHAR(250) NULL,
  `VTA_CANTIDAD` INT NULL,
  `EST_ID_ESTADO` INT NOT NULL,
  PRIMARY KEY (`VTA_ID_VENTA`),
  INDEX `fk_venta_cliente_idx` (`CLI_ID_CLIENTE` ASC) VISIBLE,
  INDEX `fk_venta_pack1_idx` (`PCK_ID_PACK` ASC) VISIBLE,
  INDEX `fk_venta_Bancos1_idx` (`BAN_ID_BANCO` ASC) VISIBLE,
  INDEX `fk_venta_COMUNA1_idx` (`COM_ID_COMUNA` ASC) VISIBLE,
  INDEX `fk_Venta_Estado_Venta1_idx` (`EST_ID_ESTADO` ASC) VISIBLE,
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`CLI_ID_CLIENTE`)
    REFERENCES `RafaySusColores`.`Cliente` (`CLI_ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_pack1`
    FOREIGN KEY (`PCK_ID_PACK`)
    REFERENCES `RafaySusColores`.`Pack` (`PCK_ID_PACK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_Bancos1`
    FOREIGN KEY (`BAN_ID_BANCO`)
    REFERENCES `RafaySusColores`.`Bancos` (`BAN_ID_BANCO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_COMUNA1`
    FOREIGN KEY (`COM_ID_COMUNA`)
    REFERENCES `RafaySusColores`.`Comuna` (`COM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Estado_Venta1`
    FOREIGN KEY (`EST_ID_ESTADO`)
    REFERENCES `RafaySusColores`.`Estado_Venta` (`EST_ID_ESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Pack` (
  `PCK_ID_PACK` INT NOT NULL AUTO_INCREMENT,
  `PCK_NOMBRE` VARCHAR(45) NOT NULL,
  `PCK_COSTO` VARCHAR(45) NOT NULL,
  `PCK_STOCK` INT NOT NULL,
  `PCK_ESTADO` BIT NULL,
  PRIMARY KEY (`PCK_ID_PACK`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Pack_has_Articulo` (
  `PCK_ID_PACK` INT NOT NULL AUTO_INCREMENT,
  `ART_ID_ARTICULO` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  PRIMARY KEY (`PCK_ID_PACK`, `ART_ID_ARTICULO`),
  INDEX `fk_pack_has_articulo_articulo1_idx` (`ART_ID_ARTICULO` ASC) VISIBLE,
  INDEX `fk_pack_has_articulo_pack1_idx` (`PCK_ID_PACK` ASC) VISIBLE,
  CONSTRAINT `fk_pack_has_articulo_pack1`
    FOREIGN KEY (`PCK_ID_PACK`)
    REFERENCES `RafaySusColores`.`Pack` (`PCK_ID_PACK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pack_has_articulo_articulo1`
    FOREIGN KEY (`ART_ID_ARTICULO`)
    REFERENCES `RafaySusColores`.`Articulo` (`ART_ID_ARTICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Articulo` (
  `ART_ID_ARTICULO` INT NOT NULL AUTO_INCREMENT,
  `ART_DESCRIPCION` VARCHAR(45) NOT NULL,
  `ART_STOCK` INT NOT NULL,
  `ART_FECHA_VENCIMIENTO` DATE NOT NULL,
  `ART_ESTADO` BIT NULL,
  `Categoria_CAT_ID_CATEGORIA` INT NOT NULL,
  `Proveedor_PRO_ID_PROVEEDOR` INT NOT NULL,
  `MAR_ID` INT NULL,
  PRIMARY KEY (`ART_ID_ARTICULO`, `Categoria_CAT_ID_CATEGORIA`, `Proveedor_PRO_ID_PROVEEDOR`),
  INDEX `fk_Articulo_Categoria1_idx` (`Categoria_CAT_ID_CATEGORIA` ASC) VISIBLE,
  INDEX `fk_Articulo_Proveedor1_idx` (`Proveedor_PRO_ID_PROVEEDOR` ASC) VISIBLE,
  INDEX `fk_Articulo_Marcas_idx` (`MAR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Articulo_Categoria1`
    FOREIGN KEY (`Categoria_CAT_ID_CATEGORIA`)
    REFERENCES `RafaySusColores`.`Categoria` (`CAT_ID_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_Proveedor1`
    FOREIGN KEY (`Proveedor_PRO_ID_PROVEEDOR`)
    REFERENCES `RafaySusColores`.`Proveedor` (`PRO_ID_PROVEEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_Marcas`
    FOREIGN KEY (`MAR_ID`)
    REFERENCES `RafaySusColores`.`Marcas` (`MAR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`FacturaDetalle` (
  `DET_ID_DETALLE` INT NOT NULL AUTO_INCREMENT,
  `FAC_ID_FACTURA` INT NOT NULL,
  `ART_ID_ARTICULO` INT NOT NULL,
  `DET_FECHA_VENCIMIENTO` DATE NOT NULL,
  `DET_CANTIDAD` INT NOT NULL,
  `DET_VALOR` INT NOT NULL,
  PRIMARY KEY (`DET_ID_DETALLE`),
  INDEX `fk_articulo_has_Factura_Factura1_idx` (`FAC_ID_FACTURA` ASC) VISIBLE,
  INDEX `fk_FacturaDetalle_articulo1_idx` (`ART_ID_ARTICULO` ASC) VISIBLE,
  CONSTRAINT `fk_articulo_has_Factura_Factura1`
    FOREIGN KEY (`FAC_ID_FACTURA`)
    REFERENCES `RafaySusColores`.`Factura` (`FAC_ID_FACTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaDetalle_articulo1`
    FOREIGN KEY (`ART_ID_ARTICULO`)
    REFERENCES `RafaySusColores`.`Articulo` (`ART_ID_ARTICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Factura` (
  `FAC_ID_FACTURA` INT NOT NULL AUTO_INCREMENT,
  `FAC_NUMERO` INT NOT NULL,
  `FAC_FECHA_FACTURA` DATE NOT NULL,
  `ORC_ID_ORDEN` INT NULL,
  PRIMARY KEY (`FAC_ID_FACTURA`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Orden_Compra` (
  `ORC_ID_ORDEN` INT NOT NULL AUTO_INCREMENT,
  `ORC_FECHA_ORDEN` DATE NULL,
  `Factura_FAC_ID_FACTURA` INT NOT NULL,
  PRIMARY KEY (`ORC_ID_ORDEN`, `Factura_FAC_ID_FACTURA`),
  INDEX `fk_Orden_Compra_Factura1_idx` (`Factura_FAC_ID_FACTURA` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_Compra_Factura1`
    FOREIGN KEY (`Factura_FAC_ID_FACTURA`)
    REFERENCES `RafaySusColores`.`Factura` (`FAC_ID_FACTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `RafaySusColores`.`Orden_Compra_Detalle` (
  `OCD_ID_DETALLE` INT NOT NULL AUTO_INCREMENT,
  `ART_ID_ARTICULO` INT NULL,
  `OCD_CANTIDAD` INT NULL,
  `OCD_DET_VALOR` INT NULL,
  `Orden_Compra_ORC_ID_ORDEN` INT NOT NULL,
  `Articulo_ART_ID_ARTICULO` INT NOT NULL,
  PRIMARY KEY (`OCD_ID_DETALLE`, `Orden_Compra_ORC_ID_ORDEN`, `Articulo_ART_ID_ARTICULO`),
  INDEX `fk_Orden_Compra_Detalle_Orden_Compra1_idx` (`Orden_Compra_ORC_ID_ORDEN` ASC) VISIBLE,
  INDEX `fk_Orden_Compra_Detalle_Articulo1_idx` (`Articulo_ART_ID_ARTICULO` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_Compra_Detalle_Orden_Compra1`
    FOREIGN KEY (`Orden_Compra_ORC_ID_ORDEN`)
    REFERENCES `RafaySusColores`.`Orden_Compra` (`ORC_ID_ORDEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_Compra_Detalle_Articulo1`
    FOREIGN KEY (`Articulo_ART_ID_ARTICULO`)
    REFERENCES `RafaySusColores`.`Articulo` (`ART_ID_ARTICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB